{
  config,
  lib,
  pkgs,
  options,
  ...
}:

let
  cfg = config.services.ucodenix;
in
{
  options.services.ucodenix = {
    enable = lib.mkEnableOption "ucodenix service";

    cpuModelId = lib.mkOption {
      type = lib.types.either lib.types.str lib.types.path;
      example = "\"auto\" or \"00A20F12\" or \"/path/to/facter.json\"";
      default = "auto";
      description = ''
        Specifies the CPU model ID to determine the appropriate microcode binary file.
        Accepts a literal model ID (e.g., "00A20F12") or a path to a `facter.json` file
        generated by `nixos-facter` to extract the model ID. Defaults to "auto", which processes
        all available microcode binaries.
      '';
    };

    cpu-microcodes = lib.mkOption {
      type = lib.types.path;
      default =
        if builtins ? fetchTree then
          import ../fetch-tree-cpu-microcodes.nix
        else
          throw ''
            default value for `services.ucodenix.cpu-microcodes` provided only when `builtins ? fetchTree`.
          '';
      defaultText = ''
        When `builtins ? fetchTree` the default value is fetched using
        `fetchTree` according to ucodenix project's `flake.lock`.
        See ucodenix documentation and
        [`builtins.fetchTree` documentation](https://releases.nixos.org/nix/nix-2.34.7/manual/language/builtins.html#builtins-fetchTree).
      '';
      description = ''
        Path to content of https://github.com/platomav/CPUMicrocodes.
      '';
      example =
        # nix
        ''
          pkgs.fetchFromGitHub {
            owner = "platomav";
            repo = "CPUMicrocodes";
            rev = "8554c59e05ae66661ebd4b33770679313888574f";
            hash = "";
          }
        '';
    };
  };

  config = lib.mkIf cfg.enable (
    let
      hasOverrideOption = lib.hasAttrByPath [ "hardware" "cpu" "amd" "microcodePackage" ] options;
    in
    lib.mkMerge [
      {
        warnings =
          lib.optional (!(builtins.elem "microcode.amd_sha_check=off" config.boot.kernelParams))
            "ucodenix: Kernel microcode checksum verification is active. This may prevent microcode from loading. Consider disabling it by setting `boot.kernelParams = [ \"microcode.amd_sha_check=off\" ];` in your configuration.";

        nixpkgs.overlays = [
          (final: prev: {
            ucodenix = final.callPackage ../pkgs/ucodenix {
              inherit (cfg) cpu-microcodes cpuModelId;
            };
            microcode-amd-ucodenix = final.callPackage ../pkgs/microcode-amd-ucodenix {
              ucodenix = final.ucodenix;
            };
          })
        ];

        hardware.cpu.amd.updateMicrocode = true;
      }

      (lib.optionalAttrs hasOverrideOption {
        hardware.cpu.amd.microcodePackage = pkgs.microcode-amd-ucodenix;
      })

      (lib.optionalAttrs (!hasOverrideOption) {
        nixpkgs.overlays = [
          (final: prev: {
            microcode-amd = final.microcode-amd-ucodenix;
          })
        ];
      })
    ]
  );

  imports = [
    (lib.mkRemovedOptionModule [ "services" "ucodenix" "cpuSerialNumber" ]
      "Please use `ucodenix.cpuModelId` instead. This option takes a different format, refer to the documentation to obtain your `cpuModelId`."
    )
  ];
}
