{
  description = "Microcode updates for AMD CPUs on NixOS";

  inputs.cpu-microcodes = {
    url = "github:platomav/CPUMicrocodes";
    flake = false;
  };

  outputs =
    { self, cpu-microcodes, ... }:
    let

      microcode-amd-pkg =
        {
          stdenv,
          libarchive,
          ucodenix,
        }:
        stdenv.mkDerivation {
          name = "amd-ucode";
          src = ucodenix;

          nativeBuildInputs = [ libarchive ];

          installPhase = ''
            mkdir -p $out
            touch -d @$SOURCE_DATE_EPOCH kernel/x86/microcode/AuthenticAMD.bin
            echo kernel/x86/microcode/AuthenticAMD.bin | bsdtar --uid 0 --gid 0 -cnf - -T - | bsdtar --null -cf - --format=newc @- > $out/amd-ucode.img
          '';
        };

    in
    {
      nixosModules.default =
        {
          config,
          lib,
          pkgs,
          options,
          ...
        }:

        let
          cfg = config.services.ucodenix;
        in
        {
          options.services.ucodenix = {
            enable = lib.mkEnableOption "ucodenix service";

            cpuModelId = lib.mkOption {
              type = lib.types.either lib.types.str lib.types.path;
              example = "\"auto\" or \"00A20F12\" or \"/path/to/facter.json\"";
              default = "auto";
              description = ''
                Specifies the CPU model ID to determine the appropriate microcode binary file.
                Accepts a literal model ID (e.g., "00A20F12") or a path to a `facter.json` file
                generated by `nixos-facter` to extract the model ID. Defaults to "auto", which processes
                all available microcode binaries.
              '';
            };
          };

          config = lib.mkIf cfg.enable (
            let
              hasOverrideOption = lib.hasAttrByPath [ "hardware" "cpu" "amd" "microcodePackage" ] options;
            in
            lib.mkMerge [
              {
                warnings =
                  lib.optional (!(builtins.elem "microcode.amd_sha_check=off" config.boot.kernelParams))
                    "ucodenix: Kernel microcode checksum verification is active. This may prevent microcode from loading. Consider disabling it by setting `boot.kernelParams = [ \"microcode.amd_sha_check=off\" ];` in your configuration.";

                nixpkgs.overlays = [
                  (final: prev: {
                    ucodenix = final.callPackage ./pkgs/ucodenix {
                      inherit cpu-microcodes;
                      inherit (cfg) cpuModelId;
                    };
                    microcode-amd-ucodenix = final.callPackage microcode-amd-pkg {
                      ucodenix = final.ucodenix;
                    };
                  })
                ];

                hardware.cpu.amd.updateMicrocode = true;
              }

              (lib.optionalAttrs hasOverrideOption {
                hardware.cpu.amd.microcodePackage = pkgs.microcode-amd-ucodenix;
              })

              (lib.optionalAttrs (!hasOverrideOption) {
                nixpkgs.overlays = [
                  (final: prev: {
                    microcode-amd = final.microcode-amd-ucodenix;
                  })
                ];
              })
            ]
          );

          imports = [
            (lib.mkRemovedOptionModule [ "services" "ucodenix" "cpuSerialNumber" ]
              "Please use `ucodenix.cpuModelId` instead. This option takes a different format, refer to the documentation to obtain your `cpuModelId`."
            )
          ];
        };

      nixosModules.ucodenix = self.nixosModules.default;
    };
}
